import { JWT } from "google-auth-library";
import { GoogleSpreadsheet } from "google-spreadsheet";

export class Sheet {
  doc: GoogleSpreadsheet;
  constructor(sheetId: string) {
    const serviceAccountAuth = new JWT({
        // env var values here are copied from service account credentials generated by google
        // see "Authentication" section in docs for more info
        email: process.env.client_email,
        key: process.env.private_key!.split(String.raw`\n`).join('\n'),
        scopes: [
            'https://www.googleapis.com/auth/spreadsheets',
        ],
    });
    this.doc = new GoogleSpreadsheet(sheetId, serviceAccountAuth);
  }

  async addRow(row: any): Promise<boolean> {
    console.log(process.env.client_email);
    try {
      await this.doc.loadInfo();
      let sheet = this.doc.sheetsByIndex[0];
      await sheet.addRow(row, {
          insert: true,
          raw: true
      });
    } catch (e) {
      console.log('failed to add row', e)
      return false
    }
    return true
  }
}